# Generated by Django 5.2.7 on 2025-12-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='usuário',
            new_name='usuario',
        ),
    ]
