# Generated by Django 5.2.8 on 2026-01-10 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_rename_usuário_categoria_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.categoria'),
        ),
    ]
